apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ca
  namespace: org1-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-test
        namespace: flux-test
      chart: platforms/hyperledger-fabric/charts/fabric-ca-server   
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: aws
        cloudNativeServices: false
        kubernetesUrl: https://127.0.0.1:6443
      vault:
        type: hashicorp
        network: fabric
        address: http://localhost:8200
        authPath: testorg1
        secretEngine: secretsv2
        secretPrefix: "data/testorg1"
        role: vault-role
        tls: false
      proxy:
        provider: none
        externalUrlSuffix: test.local.com

    storage:
      size: 512Mi
      reclaimPolicy: "Delete"
      volumeBindingMode: Immediate
      allowedTopologies:
        enabled: false

    image:
      alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
      ca: ghcr.io/hyperledger/bevel-fabric-ca:1.4.8
      pullSecret: ""

    server:
      removeCertsOnDelete: true
      tlsStatus: true
      adminUsername: org1-admin
      adminPassword: org1-adminpw
      subject: "/C=BR/ST=SP/L=SaoPaulo/O=Org1/CN=ca.org1-net"
      clusterIpPort: 7054

